/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Actions: typeof import('./src/components/form-designer/setting/actions.vue')['default']
    Clear: typeof import('./src/components/form-designer/tools/clear.vue')['default']
    ClearPage: typeof import('./src/components/form-designer/tools/clear-page.vue')['default']
    CodeEditor: typeof import('./src/components/form-designer/setting/property-editor/code-editor.vue')['default']
    ColWidget: typeof import('./src/components/form-designer/widget/col-widget/index.vue')['default']
    CopyableEditor: typeof import('./src/components/form-designer/setting/property-editor/copyable-editor.vue')['default']
    DataSource: typeof import('./src/components/form-designer/setting/data-source.vue')['default']
    DataTableWidget: typeof import('./src/components/form-designer/widget/data-table-widget/index.vue')['default']
    DialogWidget: typeof import('./src/components/form-designer/widget/dialog-widget/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElTag: typeof import('element-plus/es')['ElTag']
    Event: typeof import('./src/components/form-designer/setting/event.vue')['default']
    ExportJson: typeof import('./src/components/form-designer/tools/export-json.vue')['default']
    ExportSfc: typeof import('./src/components/form-designer/tools/more/export-sfc.vue')['default']
    ExportSFC: typeof import('./src/components/form-designer/tools/export-SFC.vue')['default']
    FormDesigner: typeof import('./src/components/form-designer/index.vue')['default']
    FormItemWidget: typeof import('./src/components/form-designer/widget/form-item-widget/index.vue')['default']
    FormRender: typeof import('./src/components/form-render/index.vue')['default']
    FormWidget: typeof import('./src/components/form-designer/widget/form-widget/index.vue')['default']
    Global: typeof import('./src/components/form-designer/setting/global.vue')['default']
    ImportJson: typeof import('./src/components/form-designer/tools/import-json.vue')['default']
    InputWidget: typeof import('./src/components/form-designer/widget/input-widget/index.vue')['default']
    LayerTree: typeof import('./src/components/form-designer/tools/layer-tree.vue')['default']
    More: typeof import('./src/components/form-designer/tools/more/index.vue')['default']
    Preview: typeof import('./src/components/form-designer/tools/preview.vue')['default']
    PreviewPage: typeof import('./src/components/form-designer/tools/preview-page.vue')['default']
    Propss: typeof import('./src/components/form-designer/setting/propss.vue')['default']
    Redo: typeof import('./src/components/form-designer/tools/redo.vue')['default']
    RowWidget: typeof import('./src/components/form-designer/widget/row-widget/index.vue')['default']
    SelectWidget: typeof import('./src/components/form-designer/widget/select-widget/index.vue')['default']
    Setting: typeof import('./src/components/form-designer/setting/index.vue')['default']
    Sider: typeof import('./src/components/form-designer/sider/index.vue')['default']
    SimpleContainerWidget: typeof import('./src/components/form-designer/widget/simple-container-widget/index.vue')['default']
    SlotWidget: typeof import('./src/components/form-designer/widget/slot-widget/index.vue')['default']
    TableWidget: typeof import('./src/components/form-designer/widget/table-widget/index.vue')['default']
    Tools: typeof import('./src/components/form-designer/tools/index.vue')['default']
    Undo: typeof import('./src/components/form-designer/tools/undo.vue')['default']
  }
}
