/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Actions: typeof import('./src/components/designer/actions.vue')['default']
    Clear: typeof import('./src/components/designer/tools/clear.vue')['default']
    ComponentDrag: typeof import('./src/components/designer/component-drag.vue')['default']
    ComponentRender: typeof import('./src/components/designer/component-render.vue')['default']
    DataSource: typeof import('./src/components/designer/data-source.vue')['default']
    Designer: typeof import('./src/components/designer/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    Events: typeof import('./src/components/designer/events.vue')['default']
    ExportJson: typeof import('./src/components/designer/tools/export-json.vue')['default']
    ExportSFC: typeof import('./src/components/designer/tools/export-SFC.vue')['default']
    FoldedPanel: typeof import('./src/components/folded-panel/index.vue')['default']
    Global: typeof import('./src/components/designer/global.vue')['default']
    ImportJson: typeof import('./src/components/designer/tools/import-json.vue')['default']
    LayerTree: typeof import('./src/components/designer/tools/layer-tree.vue')['default']
    Preview: typeof import('./src/components/designer/tools/preview.vue')['default']
    Props: typeof import('./src/components/designer/props.vue')['default']
    Redo: typeof import('./src/components/designer/tools/redo.vue')['default']
    Render: typeof import('./src/components/render/index.vue')['default']
    SvgIcon: typeof import('./src/components/svg-icon/index.vue')['default']
    Tools: typeof import('./src/components/designer/tools/index.vue')['default']
    Undo: typeof import('./src/components/designer/tools/undo.vue')['default']
    VEasyForm: typeof import('./src/components/v-easy-form/index.vue')['default']
    VTable: typeof import('./src/components/v-table/index.vue')['default']
  }
}
