/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Actions: typeof import('./src/components/designer/settings/actions/index.vue')['default']
    Button: typeof import('./src/components/button/index.vue')['default']
    CanvasDrag: typeof import('./src/components/designer/canvas-drag/index.vue')['default']
    Clear: typeof import('./src/components/designer/tools/clear.vue')['default']
    CodeEditor: typeof import('./src/components/code-editor/index.vue')['default']
    ComponentRender: typeof import('./src/components/designer/canvas-drag/component-render.vue')['default']
    ComponentRender1: typeof import('./src/components/designer/component-render1.vue')['default']
    DataSources: typeof import('./src/components/designer/settings/data-sources/index.vue')['default']
    Designer: typeof import('./src/components/designer/index.vue')['default']
    EasyForm: typeof import('./src/components/easy-form/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    EventBinder: typeof import('./src/components/designer/settings/events/event-binder.vue')['default']
    Events: typeof import('./src/components/designer/settings/events/index.vue')['default']
    ExportJson: typeof import('./src/components/designer/tools/export-json.vue')['default']
    ExportSFC: typeof import('./src/components/designer/tools/export-SFC.vue')['default']
    FoldedPanel: typeof import('./src/components/folded-panel/index.vue')['default']
    Global: typeof import('./src/components/designer/settings/global/index.vue')['default']
    ImportJson: typeof import('./src/components/designer/tools/import-json.vue')['default']
    LayerTree: typeof import('./src/components/designer/tools/layer-tree.vue')['default']
    Preview: typeof import('./src/components/designer/tools/preview.vue')['default']
    PropBinder: typeof import('./src/components/designer/settings/props/prop-binder.vue')['default']
    Props: typeof import('./src/components/designer/settings/props/index.vue')['default']
    Redo: typeof import('./src/components/designer/tools/redo.vue')['default']
    Render: typeof import('./src/components/render/index.vue')['default']
    SvgIcon: typeof import('./src/components/svg-icon/index.vue')['default']
    Tools: typeof import('./src/components/designer/tools/index.vue')['default']
    Undo: typeof import('./src/components/designer/tools/undo.vue')['default']
  }
}
